language: shell
os: linux
dist: xenial

script:
  ###
  # Permission error on script
  # Travis would spit out the below three lines.
  # $ ./tests.sh
  # /home/travis/.travis/functions: line 109: ./tests.sh: Permission denied
  # The command "./tests.sh" exited with 126.
  # 
  # The following fix does NOT seem to work
  # (base) to@mx:~/gits/word-of-day$ git ls-tree HEAD
  # 100644 blob 6319bec2a938dd8889713e671c41bdb6b551de26	.travis.yml
  # 100644 blob 51b18666e62d92c2635ad88dfb378b57be280ccf	README.md
  # 100644 blob db00954d8629e6d7a6776b076b13a0287dbb4c16	english_words.txt
  # 100644 blob 162e14b0b2db8d4a1bb582cfd8e686834337b106	german_words.txt
  # 100644 blob a20398084fbfce22eccd374152868637bcf308c4	tests.sh
  # 100755 blob b5dd165d2d299b6827e37133934387208f0e9742	word_of_the_day.sh
  # (base) to@mx:~/gits/word-of-day$ git update-index --chmod=+x tests.sh
  # (base) to@mx:~/gits/word-of-day$ git ls-tree HEAD
  # 100644 blob 6319bec2a938dd8889713e671c41bdb6b551de26	.travis.yml
  # 100644 blob 51b18666e62d92c2635ad88dfb378b57be280ccf	README.md
  # 100644 blob db00954d8629e6d7a6776b076b13a0287dbb4c16	english_words.txt
  # 100644 blob 162e14b0b2db8d4a1bb582cfd8e686834337b106	german_words.txt
  # 100644 blob a20398084fbfce22eccd374152868637bcf308c4	tests.sh
  # 100755 blob b5dd165d2d299b6827e37133934387208f0e9742	word_of_the_day.sh
  # (base) to@mx:~/gits/word-of-day$ git commit -m "permission access for test.sh"
  # [main 667d69c] permission access for test.sh
  #  1 file changed, 0 insertions(+), 0 deletions(-)
  #  mode change 100644 => 100755 tests.sh
  - chmod +x ./tests.sh

  # nullglob: If set, Bash allows filename patterns which match no files to expand to a null string, rather than themselves.
  # globstar: If set, the pattern ‘**’ used in a filename expansion context will match all files and 
  #           zero or more directories and subdirectories. If the pattern is followed by a ‘/’, only directories and subdirectories match.
  # https://www.shellcheck.net/ to lint *sh scripts. `-x` allows Shellcheck to follow sourced files
  - bash -c 'shopt -s globstar nullglob; shellcheck -x **/*.{sh,ksh,bash}'

addons:
  firefox: latest
  # Despite the below, Travis seems to be able to install
  # [0Ktravis_fold:start:install_firefox
  # [0K[33;1mInstalling Firefox latest[0m
  # $ export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-latest&lang=en-US&os=linux64'
  # travis_time:start:2d094ff6
  # [0K$ wget --no-verbose -O /tmp/firefox-latest.tar.bz2 $FIREFOX_SOURCE_URL
  # 2020-12-21 04:35:50 URL:https://download-installer.cdn.mozilla.net/pub/firefox/releases/84.0/linux-x86_64/en-US/firefox-84.0.tar.bz2 [76402088/76402088] -> "/tmp/firefox-latest.tar.bz2" [1]
  # travis_time:end:2d094ff6:start=1608525349784117351,finish=1608525350926192821,duration=1142075470,event=prepare
  # [0K$ export PATH=${TRAVIS_HOME}/firefox-latest/firefox:$PATH
  # travis_fold:end:install_firefox
  # [0K$ firefox --version
  # XPCOMGlueLoad error for file /home/travis/firefox-latest/firefox/libmozgtk.so:
  # libgtk-3.so.0: cannot open shared object file: No such file or directory
  # Couldn't load XPCOM.

  chrome: stable
  # Cannot install Chrome properly...
  # [0Ktravis_fold:start:install_chrome
  # [0K$ export CHROME_SOURCE_URL=https://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb
  # [33;1mInstalling Google Chrome stable[0m
  # travis_time:start:0e9ac7cb
  # [0K$ wget --no-verbose -O /tmp/$(basename $CHROME_SOURCE_URL) $CHROME_SOURCE_URL
  # 2020-12-21 04:35:42 URL:https://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb [72446160/72446160] -> "/tmp/google-chrome-stable_current_amd64.deb" [1]
  # travis_time:end:0e9ac7cb:start=1608525342427693796,finish=1608525342883527701,duration=455833905,event=prepare
  # [0KSelecting previously unselected package google-chrome-stable.
  # (Reading database ... 106421 files and directories currently installed.)
  # Preparing to unpack .../google-chrome-stable_current_amd64.deb ...
  # Unpacking google-chrome-stable (87.0.4280.88-1) ...
  # dpkg: dependency problems prevent configuration of google-chrome-stable:
  #  google-chrome-stable depends on fonts-liberation; however:
  #   Package fonts-liberation is not installed.
  #  google-chrome-stable depends on libatk-bridge2.0-0 (>= 2.5.3); however:
  #   Package libatk-bridge2.0-0 is not installed.
  #  google-chrome-stable depends on libatspi2.0-0 (>= 2.9.90); however:
  #   Package libatspi2.0-0 is not installed.
  #  google-chrome-stable depends on libgbm1 (>= 8.1~0); however:
  #   Package libgbm1 is not installed.
  #  google-chrome-stable depends on libgtk-3-0 (>= 3.9.10); however:
  #   Package libgtk-3-0 is not installed.
  #  google-chrome-stable depends on libxkbcommon0 (>= 0.4.1); however:
  #   Package libxkbcommon0 is not installed.
  #  google-chrome-stable depends on xdg-utils (>= 1.0.2); however:
  #   Package xdg-utils is not installed.

  # dpkg: error processing package google-chrome-stable (--install):
  #  dependency problems - leaving unconfigured
  # Processing triggers for mime-support (3.59ubuntu1) ...
  # Processing triggers for man-db (2.7.5-1) ...
  # Errors were encountered while processing:
  #  google-chrome-stable
  # travis_fold:end:install_chrome

  ### 
  # https://github.com/codecov/example-bash
  # Deprecated key: "sudo" (The key `sudo` has no effect anymore.)
  # sudo: required
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

# jobs:
#   # Can omit the below line as it is named "Test" by default with the first letter capitalised
#   stage: Test
#   name: "Unit testing"

deploy:
  provider: pages # Push to GitHub
  keep_history: true
  
  # Deprecated key: "skip_cleanup" (not supported in dpl v2, use cleanup)
  # skip_cleanup: true 
  
  # 'false' makes Travis CI delete all the files created during the build,
  #   which will probably delete what I am going to upload!
  github_token: $GITHUB_TOKEN
  # Go to Settings | Developer Settings | Personal Access Tokens on GitHub. Copy that and plug that as 'GITHUB_TOKEN' in 
  #  Settings | Environment Variables on Travis-ci.com
  on:
    branch: main
  # Or,  target_branch: master?

notifications:
  # By default, a build email is sent to the committer and the author, but
  #  only if they have access to the repository the commit was pushed to
  email:
    recipients:
      - $PRIMARY_EMAIL_ADDRESS
      - mail@gmail.com
    on_success: always # 'change' by default when notification gets set when the build status changes
    on_failure: always # 'always' by default

# CI providers like Travis CI run tests, generate coverage and upload the coverage to Codecov for every commit.
# Need to create a code coverage report (.xml) in bash.  Codecov ingests reports, does not run tests.
after_success:
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage ./tests.sh &&
  bash <(curl -s https://codecov.io/bash) -v